export interface Keyword {
  kw: string;
  score: number;
  cat: string;
  monthly: string;
  pinned?: boolean;
  tags: string[];
}

export const KW_DATABASE: Keyword[] = [
  // PINNED (luôn xuất hiện)
  {kw:"tư vấn tâm lý",   score:999,cat:"Cố định",monthly:">100K",pinned:true,tags:["tâm lý","tư vấn"]},
  {kw:"kỹ năng sống",    score:998,cat:"Cố định",monthly:">100K",pinned:true,tags:["kỹ năng","sống"]},

  // VOLUME RẤT CAO (80-100 → >50K/tháng)
  {kw:"dạy con",score:100,cat:"Nuôi dạy con",monthly:">100K",tags:["nuôi con","dạy dỗ"]},
  {kw:"nuôi con",score:98,cat:"Nuôi dạy con",monthly:">100K",tags:["nuôi dưỡng","chăm sóc con"]},
  {kw:"tâm lý trẻ em",score:96,cat:"Tâm lý trẻ",monthly:"50K–100K",tags:["tâm lý","trẻ em"]},
  {kw:"trẻ bướng bỉnh",score:95,cat:"Hành vi trẻ",monthly:"50K–100K",tags:["bướng bỉnh","khó bảo"]},
  {kw:"con không nghe lời",score:94,cat:"Hành vi trẻ",monthly:"50K–100K",tags:["không nghe lời"]},
  {kw:"làm cha mẹ",score:93,cat:"Kỹ năng cha mẹ",monthly:"50K–100K",tags:["cha mẹ","phụ huynh"]},
  {kw:"dạy con tuổi teen",score:92,cat:"Tuổi teen",monthly:"50K–100K",tags:["teen","tuổi teen"]},
  {kw:"tâm lý tuổi dậy thì",score:91,cat:"Tuổi teen",monthly:"50K–100K",tags:["dậy thì","tuổi teen"]},
  {kw:"cách dạy con",score:90,cat:"Nuôi dạy con",monthly:"50K–100K",tags:["cách dạy","phương pháp"]},
  {kw:"con nghiện điện thoại",score:89,cat:"Hành vi trẻ",monthly:"30K–80K",tags:["nghiện phone","điện thoại"]},
  {kw:"trẻ em và mạng xã hội",score:85,cat:"Hành vi trẻ",monthly:"20K–60K",tags:["mạng xã hội","social media"]},
  {kw:"phương pháp dạy con",score:88,cat:"Nuôi dạy con",monthly:"30K–80K",tags:["phương pháp","dạy con"]},
  {kw:"con lười học",score:87,cat:"Học tập",monthly:"30K–70K",tags:["lười học","học hành"]},
  {kw:"dạy con kỹ năng sống",score:86,cat:"Kỹ năng sống",monthly:"30K–60K",tags:["kỹ năng sống"]},
  {kw:"cha mẹ và con cái",score:85,cat:"Kỹ năng cha mẹ",monthly:"30K–60K",tags:["cha mẹ","con cái"]},
  {kw:"chữa lành",score:84,cat:"Tâm lý trẻ",monthly:"20K–70K",tags:["chữa lành","healing"]},
  {kw:"nghiện game",score:82,cat:"Hành vi trẻ",monthly:"20K–60K",tags:["nghiện game","gaming"]},
  {kw:"con chơi game nhiều",score:76,cat:"Hành vi trẻ",monthly:"10K–30K",tags:["game","chơi game"]},
  {kw:"ba mẹ và con tuổi teen",score:75,cat:"Tuổi teen",monthly:"10K–40K",tags:["ba mẹ","teen"]},
  {kw:"giáo dục giới tính",score:75,cat:"Nuôi dạy con",monthly:"10K–35K",tags:["giới tính","dậy thì"]},

  // VOLUME CAO (60-79 → 10K–50K)
  {kw:"hiểu con",score:79,cat:"Kỹ năng cha mẹ",monthly:"10K–50K",tags:["hiểu trẻ","đồng cảm"]},
  {kw:"kết nối với con",score:78,cat:"Kỹ năng cha mẹ",monthly:"10K–50K",tags:["kết nối"]},
  {kw:"trẻ nổi loạn",score:77,cat:"Tuổi teen",monthly:"10K–50K",tags:["nổi loạn","teen"]},
  {kw:"con không nghe lời cha mẹ",score:76,cat:"Hành vi trẻ",monthly:"10K–50K",tags:["không nghe lời"]},
  {kw:"trẻ thiếu tự tin",score:75,cat:"Tâm lý trẻ",monthly:"10K–50K",tags:["tự tin","thiếu tự tin"]},
  {kw:"con hay nói dối",score:74,cat:"Hành vi trẻ",monthly:"10K–50K",tags:["nói dối"]},
  {kw:"đứa trẻ bướng bỉnh",score:74,cat:"Hành vi trẻ",monthly:"10K–30K",tags:["bướng bỉnh"]},
  {kw:"cách nói chuyện với con",score:73,cat:"Kỹ năng cha mẹ",monthly:"10K–50K",tags:["nói chuyện","giao tiếp"]},
  {kw:"tâm lý học trẻ em",score:63,cat:"Tâm lý trẻ",monthly:"10K–30K",tags:["tâm lý học"]},
  {kw:"nuôi dạy con tích cực",score:62,cat:"Nuôi dạy con",monthly:"10K–30K",tags:["tích cực"]},
  {kw:"trẻ lo lắng",score:60,cat:"Tâm lý trẻ",monthly:"5K–20K",tags:["lo âu","stress"]},
  {kw:"áp lực học tập",score:72,cat:"Học tập",monthly:"8K–25K",tags:["áp lực","học tập"]},
  {kw:"tư vấn tâm lý trẻ em",score:72,cat:"Tư vấn tâm lý",monthly:"8K–25K",tags:["tư vấn","tâm lý"]},
  {kw:"cảm xúc tuổi teen",score:68,cat:"Tuổi teen",monthly:"8K–25K",tags:["cảm xúc","teen"]},
  {kw:"trẻ em hạnh phúc",score:66,cat:"Tâm lý trẻ",monthly:"6K–18K",tags:["hạnh phúc"]},
  {kw:"kỹ năng nuôi con",score:70,cat:"Kỹ năng cha mẹ",monthly:"7K–22K",tags:["kỹ năng","nuôi con"]},
  {kw:"cha mẹ độc hại",score:70,cat:"Tâm lý trẻ",monthly:"8K–25K",tags:["toxic","độc hại"]},
  {kw:"vết thương tuổi thơ",score:68,cat:"Tâm lý trẻ",monthly:"6K–20K",tags:["trauma","vết thương"]},
  {kw:"sức khỏe tâm thần trẻ",score:65,cat:"Tâm lý trẻ",monthly:"5K–18K",tags:["tâm thần","mental health"]},
  {kw:"phát triển toàn diện",score:65,cat:"Nuôi dạy con",monthly:"5K–18K",tags:["toàn diện","phát triển"]},
  {kw:"tư vấn phụ huynh",score:65,cat:"Tư vấn tâm lý",monthly:"5K–18K",tags:["tư vấn","phụ huynh"]},
  {kw:"con học kém",score:65,cat:"Học tập",monthly:"6K–18K",tags:["học kém","điểm thấp"]},
  {kw:"tạo động lực học cho con",score:60,cat:"Học tập",monthly:"5K–15K",tags:["động lực","học"]},
  {kw:"phương pháp học hiệu quả",score:70,cat:"Học tập",monthly:"10K–30K",tags:["học hiệu quả"]},
  {kw:"trẻ em và stress",score:55,cat:"Tâm lý trẻ",monthly:"3K–12K",tags:["stress","căng thẳng"]},

  // TÌNH HUỐNG CỤ THỂ (score 40-60)
  {kw:"tình huống ứng xử với con",score:55,cat:"Kỹ năng cha mẹ",monthly:"5K–15K",tags:["tình huống","ứng xử"]},
  {kw:"lắng nghe chủ động",score:45,cat:"Kỹ năng cha mẹ",monthly:"3K–8K",tags:["active listening","lắng nghe"]},
  {kw:"câu hỏi giúp trẻ mở lòng",score:42,cat:"Kỹ năng cha mẹ",monthly:"2K–8K",tags:["mở lòng","kết nối"]},
  {kw:"trẻ xa cách cha mẹ",score:55,cat:"Tâm lý trẻ",monthly:"3K–12K",tags:["xa cách","cô lập"]},
  {kw:"cha mẹ bất lực với con",score:52,cat:"Kỹ năng cha mẹ",monthly:"3K–10K",tags:["bất lực","ba mẹ"]},
  {kw:"trò chuyện cùng con",score:62,cat:"Kỹ năng cha mẹ",monthly:"5K–18K",tags:["trò chuyện","nói chuyện"]},
  {kw:"xung đột cha mẹ con cái",score:58,cat:"Kỹ năng cha mẹ",monthly:"4K–12K",tags:["xung đột","mâu thuẫn"]},
  {kw:"dạy con quản lý cảm xúc",score:52,cat:"Kỹ năng sống",monthly:"3K–10K",tags:["cảm xúc","quản lý"]},
  {kw:"kỷ luật không đòn roi",score:48,cat:"Nuôi dạy con",monthly:"2K–8K",tags:["kỷ luật tích cực","không đánh"]},
  {kw:"dạy con tự lập",score:68,cat:"Kỹ năng sống",monthly:"6K–18K",tags:["tự lập","độc lập"]},
  {kw:"dạy con biết đồng cảm",score:45,cat:"Kỹ năng sống",monthly:"2K–8K",tags:["đồng cảm","empathy"]},
  {kw:"dạy con tư duy",score:62,cat:"Kỹ năng sống",monthly:"5K–15K",tags:["tư duy","critical thinking"]},
  {kw:"EQ trẻ em",score:60,cat:"Tâm lý trẻ",monthly:"4K–12K",tags:["EQ","emotional intelligence"]},
  {kw:"não bộ trẻ em",score:66,cat:"Tâm lý trẻ",monthly:"5K–18K",tags:["não bộ","neuroscience"]},
  {kw:"phát triển cảm xúc trẻ",score:67,cat:"Tâm lý trẻ",monthly:"5K–15K",tags:["cảm xúc","EQ"]},
  {kw:"con khép kín",score:48,cat:"Tâm lý trẻ",monthly:"2K–8K",tags:["khép kín","introvert"]},
  {kw:"trẻ trầm cảm",score:56,cat:"Tâm lý trẻ",monthly:"5K–15K",tags:["trầm cảm","depression"]},
  {kw:"con bị bắt nạt",score:55,cat:"Tâm lý trẻ",monthly:"5K–15K",tags:["bắt nạt","bullying"]},
  {kw:"con không muốn học",score:64,cat:"Học tập",monthly:"6K–18K",tags:["học hành","ghét học"]},
  {kw:"con không muốn đi học",score:55,cat:"Học tập",monthly:"3K–10K",tags:["đi học"]},
  {kw:"phụ huynh lo lắng",score:52,cat:"Kỹ năng cha mẹ",monthly:"3K–10K",tags:["lo lắng","worry"]},
  {kw:"mệt mỏi vì con",score:45,cat:"Kỹ năng cha mẹ",monthly:"2K–8K",tags:["mệt mỏi","kiệt sức"]},
  {kw:"làm bạn với con",score:58,cat:"Kỹ năng cha mẹ",monthly:"4K–12K",tags:["bạn bè","thân thiết"]},
  {kw:"giao tiếp cha mẹ con cái",score:57,cat:"Kỹ năng cha mẹ",monthly:"4K–12K",tags:["giao tiếp"]},
  {kw:"cách khen con đúng cách",score:53,cat:"Kỹ năng cha mẹ",monthly:"3K–10K",tags:["khen","praise"]},
  {kw:"cách kỷ luật con",score:58,cat:"Nuôi dạy con",monthly:"4K–12K",tags:["kỷ luật"]},
  {kw:"giới hạn màn hình cho trẻ",score:55,cat:"Hành vi trẻ",monthly:"3K–10K",tags:["screen time","màn hình"]},
  {kw:"gia đình hạnh phúc",score:60,cat:"Kỹ năng cha mẹ",monthly:"5K–15K",tags:["hạnh phúc","family"]},
  {kw:"dạy con kỹ năng xã hội",score:55,cat:"Kỹ năng sống",monthly:"3K–10K",tags:["xã hội","social skills"]},
  {kw:"trẻ thiếu tình yêu thương",score:54,cat:"Tâm lý trẻ",monthly:"3K–12K",tags:["tình yêu thương"]},

  // ĐỘ TUỔI
  {kw:"trẻ 10 tuổi",score:72,cat:"Độ tuổi",monthly:"10K–30K",tags:["10 tuổi","tiểu học"]},
  {kw:"trẻ 12 tuổi",score:71,cat:"Độ tuổi",monthly:"10K–30K",tags:["12 tuổi"]},
  {kw:"trẻ 15 tuổi",score:70,cat:"Độ tuổi",monthly:"10K–25K",tags:["15 tuổi","teen"]},
  {kw:"tuổi 10 đến 18",score:60,cat:"Độ tuổi",monthly:"5K–15K",tags:["10-18","teen"]},
  {kw:"nuôi dạy con trai tuổi teen",score:58,cat:"Tuổi teen",monthly:"4K–12K",tags:["con trai","teen"]},
  {kw:"nuôi dạy con gái tuổi teen",score:57,cat:"Tuổi teen",monthly:"4K–12K",tags:["con gái","teen"]},
  {kw:"trẻ hay ăn vạ",score:65,cat:"Hành vi trẻ",monthly:"6K–18K",tags:["ăn vạ","tantrum"]},
  {kw:"trẻ hay khóc",score:51,cat:"Hành vi trẻ",monthly:"3K–10K",tags:["khóc","hay khóc"]},
  {kw:"con nổi giận",score:60,cat:"Hành vi trẻ",monthly:"4K–12K",tags:["nổi giận","tức giận"]},
  {kw:"con không chia sẻ với ba mẹ",score:50,cat:"Hành vi trẻ",monthly:"3K–10K",tags:["không chia sẻ","xa cách"]},
  {kw:"con sập cửa",score:38,cat:"Tuổi teen",monthly:"1K–5K",tags:["sập cửa","teen nổi giận"]},
  {kw:"ứng xử với trẻ tuổi teen",score:55,cat:"Tuổi teen",monthly:"3K–10K",tags:["ứng xử","teen"]},
  {kw:"trao đổi với con",score:50,cat:"Kỹ năng cha mẹ",monthly:"3K–8K",tags:["trao đổi","nói chuyện"]},
  {kw:"không gian an toàn cho con",score:40,cat:"Tâm lý trẻ",monthly:"1K–5K",tags:["an toàn","safe space"]},
  {kw:"15 phút kết nối con",score:37,cat:"Kỹ năng cha mẹ",monthly:"1K–5K",tags:["15 phút","kết nối"]},
  {kw:"mẹ và con gái",score:55,cat:"Kỹ năng cha mẹ",monthly:"3K–10K",tags:["mẹ","con gái"]},
  {kw:"ba và con trai",score:50,cat:"Kỹ năng cha mẹ",monthly:"3K–8K",tags:["ba","bố","con trai"]},
  {kw:"con lớn bướng",score:65,cat:"Tuổi teen",monthly:"5K–15K",tags:["lớn","bướng bỉnh","teen"]},
  {kw:"con đang lớn",score:50,cat:"Tuổi teen",monthly:"3K–10K",tags:["lớn lên","phát triển"]},
  {kw:"trẻ trịch thượng",score:35,cat:"Hành vi trẻ",monthly:"1K–4K",tags:["trịch thượng","kiêu"]},
  {kw:"lắng nghe con",score:62,cat:"Kỹ năng cha mẹ",monthly:"5K–15K",tags:["lắng nghe"]},
  {kw:"sách nuôi dạy con",score:55,cat:"Nuôi dạy con",monthly:"4K–12K",tags:["sách","parenting book"]},
  {kw:"dạy con biết ơn",score:45,cat:"Kỹ năng sống",monthly:"2K–8K",tags:["biết ơn","gratitude"]},
  {kw:"con hay ganh tị",score:40,cat:"Hành vi trẻ",monthly:"1K–5K",tags:["ganh tị","jealous"]},
  {kw:"trẻ tăng động",score:55,cat:"Tâm lý trẻ",monthly:"3K–10K",tags:["ADHD","tăng động"]},
];
